services:
  app:
    image: node:22
    container_name: devcontainer_app
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000"
      - "5173:5173" # 如果用Vite開發時也可以用
    environment:
      - NODE_ENV=development