services:
  app:
    image: node:22
    container_name: devcontainer_app
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=development